# Generated by Django 4.1 on 2024-08-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='isFavorite',
            field=models.BooleanField(default=False),
        ),
    ]
